### PR TITLE
large update to 84+

### PR DESCRIPTION
**Pull request by r1tsuu**
translator plugin is already available on [1.3.0-pre.0](https://www.npmjs.com/package/@payload-enchants/translator/v/1.3.0-pre.0) version

### CODE REVIEW

**Comment by nvti** [comment]
@r1tsuu  I am waiting for this PR.

**Comment by r1tsuu** [comment]
sorry I don't have much time as I'm both a member of the Payload team and working on an another project atm

**Comment by nvti** [comment]
> sorry I don't have much time as I'm both a member of the Payload team and working on an another project atm

I know. I just wanted to let you know it is important to someone who uses your library. Payload now is "no breaking change" mode so I think it is time to upgrade. This upgrade from payload beta.6x to beta.8x is quite a lot of work, even for my small project.
If you want to help, please let me know.

**Comment by genox** [comment]
> I know. I just wanted to let you know it is important to someone who uses your library (beautiful library). Payload now is "no breaking change" mode so I think it is time to upgrade. This upgrade from payload beta.6x to beta.8x is quite a lot of work, even for my small project.
> If you want to help, please let me know.

I second that. I use at least one of the plugins in this collection on every new project I start.

**Comment by Notorious-Ali** [comment]
any updates on this pr?

`node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".scss" for C:\Users\dasme\ali\ajeman\node_modules\@payload-enchants\translator\dist\client\components\CustomButton\styles.scss
    at new NodeError (node:internal/errors:405:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:136:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:182:36)
    at defaultLoad (node:internal/modules/esm/load:101:20)
    at nextLoad (node:internal/modules/esm/hooks:864:28)
    at load (file:///C:/Users/dasme/ali/ajeman/node_modules/tsx/dist/esm/index.mjs?1729266158272:2:1768)
    at nextLoad (node:internal/modules/esm/hooks:864:28)
    at Hooks.load (node:internal/modules/esm/hooks:447:26)
    at handleMessage (node:internal/modules/esm/worker:196:24)
    at Immediate.checkForMessages (node:internal/modules/esm/worker:138:28) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Node.js v18.20.4
PS C:\Users\dasme\ali\ajeman> npx payload generate:importmap

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".scss" for C:\Users\dasme\ali\ajeman\node_modules\@payload-enchants\translator\dist\client\components\CustomButton\styles.scss
    at new NodeError (node:internal/errors:405:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:136:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:182:36)
    at defaultLoad (node:internal/modules/esm/load:101:20)
    at nextLoad (node:internal/modules/esm/hooks:864:28)
    at load (file:///C:/Users/dasme/ali/ajeman/node_modules/tsx/dist/esm/index.mjs?1729266560603:2:1768)
    at nextLoad (node:internal/modules/esm/hooks:864:28)
    at Hooks.load (node:internal/modules/esm/hooks:447:26)
    at handleMessage (node:internal/modules/esm/worker:196:24)
    at Immediate.checkForMessages (node:internal/modules/esm/worker:138:28) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
`

**Comment by azivkovi** [comment]
Without this, the package is unusable. Tbh, this functionality should be part of Payload core.

**Comment by nvti** [comment]
I just upgrade translator plugin to v3.0.0 by myself. Should I open a pr or something?

**Comment by carlcs** [comment]
@nvti could you please share your fork?

**Comment by nvti** [comment]
> @nvti could you please share your fork?

this is my fork: https://github.com/nvti/payload-enchants
**NOTE**: I added this translator plugin direct into my codebase and I just copied it into this fork to share with you guy. I don't have much time to test it. Please tell me if you faced any issue about this.

BTW, I added [libre translate](https://libretranslate.com) resolve

**Comment by r1tsuu** [comment]
> I just upgrade translator plugin to v3.0.0 by myself. Should I open a pr or something?

Hello! It would be nice, you can open with what you have and I can work on other packages in the codebase!

**Comment by nvti** [comment]
> > I just upgrade translator plugin to v3.0.0 by myself. Should I open a pr or something?
> 
> Hello! It would be nice, you can open with what you have and I can work on other packages in the codebase!

I opened #98 . I see you have test folder but I don't use it yet. This PR is based on your tag `translator-1.3.0-pre.0`

**Comment by carlcs** [comment]
Thanks @nvti, I’ve used your updates to patch our installation and it worked like a charm.

**Comment by nvti** [comment]
@carlcs I’m glad to hear that!

**Comment by r1tsuu** [comment]
Merged @nvti's PR https://github.com/r1tsuu/payload-enchants/pull/98, thank you!

I'm going to clean up now and do a release

**Comment by r1tsuu** [comment]
Relased 1.3.0 https://github.com/r1tsuu/payload-enchants/releases/tag/translator-1.3.0 that works with the latest payload 3.1.0!

**Pull request closed without merging**
